# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180330_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_text',
            field=models.TextField(default='', verbose_name='About'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budge'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('P', 'Person'), ('B', 'Business')], default='P', max_length=2, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse (URL)'),
        ),
    ]
